### ISSUE TITLE
divided by 0

### ISSUE THREAD

**Issue by yuhang-lin** [richard-moulton/D-Stream#4]
Hi!

When I used your code, I found a potential bug of 0 divided by 0:

Exception in thread "main" java.lang.ArithmeticException: / by zero
	at moa.clusterers.dstream.Dstream.trainOnInstanceImpl(Dstream.java:348)
	at moa.clusterers.AbstractClusterer.trainOnInstance(AbstractClusterer.java:131)
	at mytest.TestDStream.main(TestDStream.java:24)

My testing code is:
```Java
package mytest;

import com.yahoo.labs.samoa.instances.Instance;

import moa.cluster.Clustering;
import moa.clusterers.dstream.Dstream;
import moa.streams.clustering.ClusteringStream;
import moa.streams.clustering.FileStream;

public class TestDStream {

	public static void main(String[] args) {
		FileStream fStream = new FileStream();
		fStream.arffFileOption.setValue("test.arff");// set the ARFF file name
		fStream.normalizeOption.setValue(false);// set normalized to be true or false
		fStream.prepareForUse();
		int numLines = 0;
		//DStream
		Dstream dstream = new Dstream();
		dstream.resetLearning();
		ClusteringStream stream = fStream;
		while (stream.hasMoreInstances()) {
			Instance curr = stream.nextInstance().getData();
			dstream.trainOnInstance(curr);
			numLines++;
		}
		Clustering resDstream = dstream.getClusteringResult();
		dstream.getMicroClusteringResult();
		System.out.println("Size of result from Dstream: " + resDstream.size());
		System.out.println(numLines + " lines have been read");
	}
}
```
Thanks.

**Comment by richard-moulton** [comment]
This issue was also identified in the MOA Developers Google Group: https://groups.google.com/forum/#!topic/moa-development/3IKcguR2kOk

As mentioned there, the error uncovered occurred when the procedure to calculate **gap** produces a zero. This has been modified so that **gap** cannot be set to zero: if the procedure produces a zero, gap will instead be set to one.
